version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - aws s3 cp build s3://application-54321 --recursive
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
      - "**/*"