version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp "Application" "s3://demo-app-54321/index.html" --recursive
      - echo Build completed on `date`
      - aws cloudfront create-invalidation --distribution-id E3BMY8WLRU0YL9 --paths '/*'
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
      - "**/*"