version: 0.2
env:
  parameter-store:
    CDIN_PROD: "CDN_ID_PROD"
    S3_BUCKETPROD: "S3_BUCKET_PROD"

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp "index.html" "s3://${S3_BUCKETPROD}/index.html"
      - echo Build completed on `date`
      - aws cloudfront create-invalidation --distribution-id ${CDIN_PROD} --paths '/*'
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
      - "**/*"